---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: altertrack-secrets
  namespace: altertrack
spec:
  itemPath: "vaults/k8s-home/items/altertrack"
---
apiVersion: v1
kind: Secret
metadata:
  name: altertrack-env
  namespace: altertrack
  annotations:
    operator.1password.io/item-path: "vaults/k8s-home/items/altertrack"
    operator.1password.io/item-name: "altertrack-secrets"
type: Opaque
