---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: better-stack-collector-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/k8s-home/items/betterstack-collector"
