---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axtazia-bot
  namespace: default
  labels:
    app: axtazia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: axtazia
  template:
    metadata:
      labels:
        app: axtazia
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: bot
          image: ghcr.io/axtazer/axtazia:latest@sha256:d3d2fa7419b3ce0f7dad9b9f00b648b7aed21847fe3e80d934ecdbe2b5b8230e
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: axtazia-secrets

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: axtazia-secrets
  namespace: default
spec:
  itemPath: "vaults/k8s-home/items/axtazia-bot"
