---
apiVersion: v1
kind: Namespace
metadata:
  name: bots
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: axtazia-secrets
  namespace: bots
spec:
  itemPath: "vaults/k8s-home/items/axtazia-bot"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axtazia-bot
  namespace: bots
  labels:
    app: axtazia
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: axtazia
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: axtazia
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: bot
          image: ghcr.io/axtazer/axtazia:latest@sha256:2fabcd27367b8ae4a60afd0059fe64804830fe488b9a8d86b8f569aadfe4a3ba
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: axtazia-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
