---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: axtazia-bot
  namespace: default
  labels:
    app: axtazia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axtazia
  template:
    metadata:
      labels:
        app: axtazia
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: bot
          image: ghcr.io/axtazer/axtazia:latest@sha256:abe1cfed1af987d497151585cfc493b4dccf2e5d1b746ecf2c4a3d01b74376e8
          imagePullPolicy: Always
          env:
            # --- SECRETS ---
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: axtazia-secrets
                  key: DISCORD_TOKEN
            - name: NASA_APOD_KEY
              valueFrom:
                secretKeyRef:
                  name: axtazia-secrets
                  key: NASA_APOD_KEY
            - name: WOL_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: axtazia-secrets
                  key: WOL_API_TOKEN

            # --- CONFIG ---
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: axtazia-config
                  key: CLIENT_ID
            - name: GUILD_ID
              valueFrom:
                configMapKeyRef:
                  name: axtazia-config
                  key: GUILD_ID
            - name: OWNER_ID
              valueFrom:
                configMapKeyRef:
                  name: axtazia-config
                  key: OWNER_ID
            - name: WOL_API_URL
              valueFrom:
                configMapKeyRef:
                  name: axtazia-config
                  key: WOL_API_URL

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: axtazia-secrets
  namespace: default
spec:
  itemPath: "vaults/k8s-home/items/axtazia-bot"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: axtazia-config
  namespace: default
data:
  CLIENT_ID: "883263767813685258"
  GUILD_ID: "798235492503257148"
  OWNER_ID: "496722398310039552"
  WOL_API_URL: https://wol.castaldo.fr/wake
