---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: axtazia-tunnel
  namespace: bots
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: axtazia.axtazer.me
      http:
        paths:
          - path: /webhook/twitch
            pathType: Prefix
            backend:
              service:
                name: axtazia-bot
                port:
                  number: 3000
          - path: /oauth/callback/discord
            pathType: Prefix
            backend:
              service:
                name: axtazia-bot
                port:
                  number: 3000
