---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  itemPath: "vaults/k8s-home/items/n8n"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: n8n-db-secrets
  namespace: n8n
spec:
  itemPath: "vaults/k8s-home/items/n8n-db"
