---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  revisionHistoryLimit: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.49.2@sha256:ac7ec5621245371c85630f861813c8e7571d18eaeeec3fdea629eedc6ba48430
          env:
            - name: TZ
              value: Europe/Paris
          ports:
            - containerPort: 8080
              name: http
          args:
            - --housekeeping_interval=60s
            - --max_housekeeping_interval=65s
            - --disable_metrics=sched,tcp,udp,percpu,referenced_memory,cpu_topology,resctrl,hugetlb
            - --docker_only=true
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: var-run
              mountPath: /var/run
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 600Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: cadvisor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cadvisor
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
      metricRelabelings:
        - sourceLabels: [container_label_io_kubernetes_pod_namespace]
          regex: ".+"
          action: drop
