---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/k8s-home/items/grafana-admin"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-analytics-token
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  itemPath: "vaults/k8s-home/items/cloudflare-analytics-token"
