---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
  labels:
    app: jellyseerr
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: fix-perms
          image: busybox:latest@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
          command: ["sh", "-c", "chown -R 1000:1000 /app/config"]
          volumeMounts:
            - name: config
              mountPath: /app/config
      containers:
        - name: jellyseerr
          image: ghcr.io/seerr-team/seerr:v3.4.1@sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1
          ports:
            - containerPort: 5055
              name: http
          env:
            - name: TZ
              value: Europe/Paris
            - name: PORT
              value: "5055"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 768Mi
          volumeMounts:
            - name: config
              mountPath: /app/config
          livenessProbe:
            httpGet:
              path: /api/v1/settings/public
              port: 5055
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/settings/public
              port: 5055
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: config
          hostPath:
            path: /srv/appdata/jellyseerr
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: jellyseerr
  ports:
    - name: http
      port: 5055
      targetPort: 5055
