---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  parentRefs:
    - name: shared-gateway
      namespace: kube-system
  hostnames:
    - nas.mydomain.fr
    - harkesh.lan
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 3600s
        backendRequest: 3600s
      backendRefs:
        - name: nextcloud
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-tunnel
  namespace: nextcloud
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: nas.mydomain.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
