---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-tunnel
  namespace: authentik
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: auth.axtazer.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 9000
