---
# Gère les apps (manifests K8s bruts) — un dossier = une Application
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Axtazer/harkesh-k8s
        revision: master
        directories:
          - path: authentik
          - path: axtazer-me
          - path: bots
          - path: flo-pro
          - path: jellyfin
          - path: matrix
          - path: media-stack
          - path: monitoring
          - path: nextcloud
          - path: ntfy
          - path: pelican
          - path: shlink
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Axtazer/harkesh-k8s
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
