---
apiVersion: v1
kind: Secret
metadata:
  name: repo-prometheus-community
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-dcgm-exporter
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: dcgm-exporter
  url: https://nvidia.github.io/dcgm-exporter/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-nvidia-device-plugin
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: nvidia-device-plugin
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-betterstack
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: betterstack
  url: https://betterstackhq.github.io/collector-helm-chart
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-8gears
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: 8gears
  url: https://8gears.container-registry.com/chartrepo/library
