---
apiVersion: v1
kind: Secret
metadata:
  name: repo-prometheus-community
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-dcgm-exporter
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: dcgm-exporter
  url: https://nvidia.github.io/dcgm-exporter/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-nvidia-device-plugin
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: nvidia-device-plugin
  url: https://nvidia.github.io/k8s-device-plugin
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-cilium
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: cilium
  url: https://helm.cilium.io
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-strrl
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: strrl.dev
  url: https://helm.strrl.dev
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-8gears
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: 8gears
  enableOCI: "true"
  url: 8gears.container-registry.com/library
