---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-flo-pro
  namespace: flo-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-flo-pro
  template:
    metadata:
      labels:
        app: dev-flo-pro
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: dev-flo-pro
          image: ghcr.io/axtazer/flo-pro:dev@sha256:d920767a8d163a9e53289e7e1be64ee80075eac386ec2edc5d10b042d585f6c2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: flo-pro-env
---
apiVersion: v1
kind: Service
metadata:
  name: dev-flo-pro
  namespace: flo-pro
spec:
  selector:
    app: dev-flo-pro
  ports:
    - port: 81
      targetPort: 3000
