---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-flo-pro
  namespace: flo-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-flo-pro
  template:
    metadata:
      labels:
        app: dev-flo-pro
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: dev-flo-pro
          image: ghcr.io/axtazer/flo-pro:dev@sha256:e276acc2598ff00e8a040d7324274607a80c52734ed8d95e4b7e84fcea59cc88
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: flo-pro-env
---
apiVersion: v1
kind: Service
metadata:
  name: dev-flo-pro
  namespace: flo-pro
spec:
  selector:
    app: dev-flo-pro
  ports:
    - port: 81
      targetPort: 3000
