---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: flo-pro-env
  namespace: flo-pro
spec:
  itemPath: "vaults/k8s-home/items/flo-pro-env"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flo-pro
  namespace: flo-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flo-pro
  template:
    metadata:
      labels:
        app: flo-pro
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: flo-pro
          image: ghcr.io/axtazer/flo-pro:main@sha256:da2dd41ef6b0dcbf943d6e8ced1ab666ee389a10940262076700898d8734eacf
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: flo-pro-env
---
apiVersion: v1
kind: Service
metadata:
  name: flo-pro
  namespace: flo-pro
spec:
  selector:
    app: flo-pro
  ports:
    - port: 80
      targetPort: 3000
